// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddPlannedRoute(arg1:string,arg2:string):Promise<void>;

export function AddProject(arg1:models.Project):Promise<models.Project>;

export function ChooseFolder():Promise<string>;

export function CreatePlannedRoutes(arg1:string):Promise<void>;

export function DeletePlannedRoute(arg1:string,arg2:string):Promise<void>;

export function DeleteProjectById(arg1:string):Promise<void>;

export function EditProjectTitle(arg1:string,arg2:string):Promise<void>;

export function ErrorDialog(arg1:string):Promise<string>;

export function GetAllProjects():Promise<Array<models.Project>>;

export function GetPathSeparator():Promise<string>;

export function GetProjectById(arg1:string):Promise<models.ProjectWithRoutes>;
