// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPlannedRoute(arg1, arg2) {
  return window['go']['main']['App']['AddPlannedRoute'](arg1, arg2);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ChooseFolder() {
  return window['go']['main']['App']['ChooseFolder']();
}

export function CreatePlannedRoutes(arg1) {
  return window['go']['main']['App']['CreatePlannedRoutes'](arg1);
}

export function DeletePlannedRoute(arg1, arg2) {
  return window['go']['main']['App']['DeletePlannedRoute'](arg1, arg2);
}

export function DeleteProjectById(arg1) {
  return window['go']['main']['App']['DeleteProjectById'](arg1);
}

export function EditProjectTitle(arg1, arg2) {
  return window['go']['main']['App']['EditProjectTitle'](arg1, arg2);
}

export function ErrorDialog(arg1) {
  return window['go']['main']['App']['ErrorDialog'](arg1);
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetPathSeparator() {
  return window['go']['main']['App']['GetPathSeparator']();
}

export function GetProjectById(arg1) {
  return window['go']['main']['App']['GetProjectById'](arg1);
}
