// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function DeleteProjectById(arg1) {
  return window['go']['main']['App']['DeleteProjectById'](arg1);
}

export function EditProjectTitle(arg1, arg2) {
  return window['go']['main']['App']['EditProjectTitle'](arg1, arg2);
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}
